#! /usr/bin/env python
import sys, time, os
from helper.daemon import Daemon
from monitor import Monitor

directory = os.path.dirname(os.path.abspath(sys.argv[0]))
config_file = directory + "/config/alert_config.conf"

class ScMonitor(Daemon):
    def run(self):
        monitor = Monitor(config_file)
        monitor.run_loop()

def pid_file():
    if os.access('/var/run/', os.W_OK):
        return "/var/run/shinchan.pid"
    return os.path.expanduser("~")+ "/.shinchan.pid"
        
if __name__ == "__main__":
    daemon = ScMonitor(pid_file())
    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            daemon.restart()
        else:
            print "Unknown command"
            sys.exit(2)
        sys.exit(0)
    else:
        print "usage: %s start|stop|restart" % sys.argv[0]
        sys.exit(2)
